name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:
          - os: macos-latest
            command: ".github/workflows/val.sh"
          - os: ubuntu-latest
            command: ".github/workflows/val.sh"
            chmod: true
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
            submodules: recursive
    - if: matrix.os == 'macos-latest'
      name: Build
      run: |
        brew install htslib
        INCLUDE_DIR="-I/opt/homebrew/opt/openssl@3/include/ \
                     -I/opt/homebrew/Cellar/htslib/1.21/include/" \
            LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.4.0/lib \
                     -L/opt/homebrew/Cellar/htslib/1.21/lib" \
            make all -j
    - if: matrix.os == 'ubuntu-latest'
      name: Build
      run: |
        sudo apt-get install libhts-dev
        make all -j
    - name: Validate
      run: |
        chmod +x .github/workflows/val.sh
        ${{ matrix.command }}

